# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblog', '0004_entry_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='views',
        ),
    ]
